[package]
name = "ministdweb"
version = "0.1.0"
authors = ["Jia Ye <planet0104@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4.13"
gif = "0.10.1"

[profile.release]
lto = true #必须加，否则asm.js编译不过
opt-level = 's'
panic = 'abort'